version: '3'
services:
  nginx:
    build:
      context: ./nginx # Ruta donde est치 el Dockerfile de Nginx
    ports:
      - "80:80" # Mapea el puerto 80 del host al contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Volumen para configuraci칩n de Nginx
    depends_on:
      - apache # Asegura que Apache se levante primero

  apache:
    build:
      context: ./apache # Ruta donde est치 el Dockerfile de Apache
    volumes:
      - ./html:/var/www/html # Volumen para servir contenido din치mico HTML
    expose:
      - "80" # Exponer el puerto 80 para que Nginx pueda conectarse internamente
